name: Publish packages to PyPi
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and publish the wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build platform independent wheel 
        run: |-
          python -m build --wheel --outdir dist

      - name: Publish wheel to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist
          skip-existing: true
